import Head from "next/head"
import Editor from "../components/editor"

export default function App() {
  return (
    <div>
      <Head>
        <title>Transpose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Editor />
    </div>
  )
}
